apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "pbpf-03-setuid-bit"
spec:
  kprobes:
  - call: "security_path_chmod"
    syscall: false
    tags: [ "T1548.001", "pbpf:single" ]
    args:
    - index: 0
      type: "path"
    - index: 1
      type: "int"
    selectors:
    - matchArgs:
      - index: 1
        operator: "Mask"
        values:
        - "2048"
        - "1024"
