apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "pbpf-05-persistence-baseline"
spec:
  kprobes:
  - call: "sys_openat"
    syscall: true
    tags: [ "T1574.006", "T1053.003", "T1098.004", "pbpf:baseline" ]
    args:
    - index: 0
      type: "int"
    - index: 1
      type: "string"
    selectors:
    - matchArgs:
      - index: 1
        operator: "Prefix"
        values:
        - "/etc/ld.so.preload"
        - "/var/spool/cron/"
        - "/etc/cron.d/"
        - "/root/.ssh/authorized_keys"
