apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "pbpf-06-imds-treatment"
spec:
  kprobes:
  - call: "tcp_connect"
    syscall: false
    tags: [ "T1552.005", "pbpf:treatment" ]
    args:
    - index: 0
      type: "sock"
    selectors:
    - matchArgs:
      - index: 0
        operator: "DAddr"
        values:
        - "169.254.169.254/32"
