apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "pbpf-11-reverse-shell-baseline"
spec:
  kprobes:
  - call: "sys_connect"
    syscall: true
    tags: [ "T1059.004", "pbpf:baseline" ]
    args:
    - index: 0
      type: "int"
    - index: 1
      type: "sockaddr"
    - index: 2
      type: "int"
