apiVersion: 1

datasources:
  - name: PurpleBPF-Postgres
    uid: purplebpf-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    isDefault: true
    editable: true
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
